### ISSUE TITLE
broken links and themes

### ISSUE THREAD

**Issue by pietru2004** [plone/plone-frontend#38]
I have created plone 6 instalation using following docker compose
```
version: "3"
services:
  plone-frontend:
    image: plone/plone-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://web-server_plone-backend_1:8080/site_name
    #ports:
    #- "3000:3000"
    depends_on:
      - plone-backend

  plone-backend:
    image: plone/plone-backend:6.0
    environment:
      SITE: site_name
    volumes:
      - /srv/plone-data:/data
    ports:
    - "8085:8080"


networks:
  default:
    external:
      name: network_name
```
also all trafic goes throu nginx proxy manager that is on that network and works correctly for all other apps that go throu it.
All links get :null in them making it impossible to navigate throu website,

Also themes are unavailable in volto frontend, as well if I set up website image via backend it does not transfer to frontend
Setting site title also works only via backend
